services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-posts}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:  ./api
    command: >
      bash -c ' 
        while ! nc -zv postgres 5432; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done &&  
        alembic upgrade head && 
        python run.py
      '
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./api:/app

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./bot:/app

volumes:
  postgres_data: 