services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-posts}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DB_URL=${DB_URL}
      - SECRET_KEY=${SECRET_KEY}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    ports:
      - "8002:8002"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./api:/app

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - DB_URL=${DB_URL}
      - TG_TOKEN=${TG_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./bot:/app

volumes:
  postgres_data: 